# Generated by Django 2.1 on 2018-08-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField(default=0)),
                ('book_name', models.CharField(max_length=200)),
                ('book_author', models.CharField(max_length=200)),
            ],
        ),
    ]
